apiVersion: v1
kind: Service
metadata:
  name: randomnumber-svc1
spec:
  ports:
    - port: 8083
      protocol: TCP
      targetPort: 8080
  selector:
    app: app
  type: ClusterIP  
---
apiVersion: v1
kind: Service
metadata:
  name: randomnumber-svc2
spec:
  type: NodePort
  ports:
    - port: 8084
      protocol: TCP
      targetPort: 8080
  selector:
    app: app 

# kubectl apply -f app-service.yaml 